# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a25bc8dfc54ebcdc5a107d60388962eebfd4850ef48fe3eecf818cb4da467c5800c5fe3d1998146a26d904314761e96ff81cd8b7c9877a4fcad24e513137457b

test:
  secret_key_base: 2fdfb0d1371793c85f4469d155f1e2bd7943cba4123800c556a89ebdc3f74994be8a98c89b1004d1cc100441e38352d0c361def3de8b464e2862160828ca3e6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
